# Generated by Django 3.1.4 on 2023-02-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_index=True, max_length=100, verbose_name='Тип')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Тип статей',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Youtube_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('photo_link', models.URLField(verbose_name='Ссылка на фото')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'Новости YouTube',
                'verbose_name_plural': 'Новости YouTube',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Guitar_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=244, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guitarworld.category_articles', verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
